server:
  port: 8091

spring:
  application:
    name: producer

  kafka:
    bootstrap-servers: 192.100.100.20:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer

logging:
  level:
    org.example.producer: debug